spring:
  application:
    name: curtaincall

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/curtaincall
    username: root
    password: gmlwogmlwo7296@
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: validate
    show-sql: true

#    sql:
#      init:
#        mode: always

logging:
  level:
    org:
      springframework:
        cache: trace # Redis 사용에 대한 로그가 조회되도록 설정
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE