spring:
  application.name: curtaincall

  datasource:
    url: jdbc:mariadb://localhost:3306/curtaincall
    username: root
    password: passw0rd

  jpa:
    hibernate:
      ddl-auto: create
    properties:
        format_sql: true

  cloud:
    aws:
      credentials:
        accessKey: AKIAVWABKC4475RVVSHO
        secretKey: 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
      s3:
        bucket: curtaincall-image
      region:
        static: ap-northeast-2
      stack:
        auto: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace