spring:
  application:
    name: curtaincall

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/curtaincall
    username: root
    password: gmlwogmlwo7296@
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: validate

    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    secret-key: "32fdsafsafadsfdsafsdfdasfdasfa1dsfadsafadsfdsafsadfdsafdsafdsfasdfasdfsa"

cloud:
  aws:
    credentials:
      accessKey: "321"
      secretKey: "312"
    s3:
      bucket: curtaincall-image
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace