spring:
  application.name: curtaincall

  datasource:
    url: yourDBUrl
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: yourDBDialect
        format_sql: true

  cloud:
    aws:
      credentials:
        accessKey: test
        secretKey: test
      s3:
        bucket: test
      region:
        static: test
      stack:
        auto: false
      cloudfront:
        domainName: test

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace